In [3]:
import numpy as np
import matplotlib.pylab as plt

%matplotlib inline

In [4]:
im = plt.imread("map2.bin.png")

In [5]:
im.shape

(3072, 2048, 4)

In [6]:
im[2][2]

array([0., 0., 0., 0.], dtype=float32)

In [7]:
im.shape

(3072, 2048, 4)

In [8]:
for i in range(4):
    im[:][0][i] = 99.00

In [9]:
im.shape

(3072, 2048, 4)

In [25]:
im[:][:][1]

array([[0.        , 0.        , 0.0627451 , 0.75686276],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       ...,
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.8784314 , 0.7529412 ],
       [0.        , 0.        , 0.        , 0.        ]], dtype=float32)

In [9]:
im2 = plt.imread("polydata2.bin.png")

In [10]:
im2.shape

(9384, 2048, 4)

In [11]:
im2

array([[[0.54509807, 0.49019608, 0.5058824 , 0.75686276],
        [0.67058825, 0.14117648, 0.44705883, 0.24705882],
        [0.45490196, 0.70980394, 0.13725491, 0.2509804 ],
        ...,
        [0.7490196 , 0.83137256, 0.46666667, 0.2509804 ],
        [0.        , 0.627451  , 0.03529412, 0.23529412],
        [0.        , 0.        , 0.9882353 , 0.21960784]],

       [[0.        , 0.32156864, 0.60784316, 0.73333335],
        [0.        , 0.84705883, 0.20784314, 0.23529412],
        [0.3764706 , 0.3529412 , 0.42745098, 0.74509805],
        ...,
        [0.        , 0.        , 0.3137255 , 0.72156864],
        [0.        , 0.1764706 , 0.0627451 , 0.23529412],
        [0.10980392, 0.9882353 , 0.5019608 , 0.75686276]],

       [[0.7647059 , 0.16470589, 0.9843137 , 0.2509804 ],
        [0.44705883, 0.5411765 , 0.4627451 , 0.2509804 ],
        [0.        , 0.9411765 , 0.92156863, 0.23137255],
        ...,
        [0.        , 0.1882353 , 0.3647059 , 0.23529412],
        [0.19215687, 0.807843